import { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { MapPin, Users, Star, Clock, Phone, ChevronDown, ChevronUp } from "lucide-react";
import SuburbLink from "@/components/SuburbLink";
import { useDocumentTitle } from "@/hooks/useDocumentTitle";

const QUOTE_URL = "/quote";
const Perth = () => {
  useDocumentTitle("Perth Decking Quotes — Get 3 Free Quotes in Minutes");
  const [showAllSuburbs, setShowAllSuburbs] = useState(false);
  const handleQuoteClick = () => { window.history.pushState({}, "", QUOTE_URL); window.dispatchEvent(new PopStateEvent("popstate")); };
  const suburbs = ["Armadale", "Ashendon", "Bedfordale", "Brookdale", "Camillo", "Champion Lakes", "Doobarda", "Forrestdale", "Harrisdale", "Haynes", "Hilbert", "Karragullen", "Kelmscott", "Mount Nasura", "Mount Richon", "Piara Waters", "Roleystone", "Seville Grove", "Wungong", "Ashfield", "Bassendean", "Eden Hill", "Bedford", "Bayswater", "Embleton", "Maylands", "Morley", "Noranda", "Mount Lawley", "Ascot", "Belmont", "Cloverdale"];
  const allSuburbs = ["Kewdale", "Perth Airport", "Redcliffe", "Rivervale", "City Beach", "Floreat", "Jolimont", "Mount Claremont", "Subiaco", "Wembley", "Wembley Downs", "West Leederville", "Bentley", "Canning Vale", "Cannington", "East Cannington", "Ferndale", "Leeming", "Lynwood", "Parkwood", "Queens Park", "Riverton", "Rossmoyne", "Shelley", "St James", "Welshpool", "Willetton", "Wilson", "Claremont", "Swanbourne"];
  const stats = [{ icon: Users, label: "Decks Quoted", value: "1,100+" }, { icon: Star, label: "Average Rating", value: "4.9/5" }, { icon: Clock, label: "Years Experience", value: "11+" }, { icon: MapPin, label: "Suburbs Serviced", value: "331+" }];
  const recentProjects = [{ suburb: "Fremantle", type: "Timber Deck", rating: 5, review: "Outstanding service and attention to detail. The team showed up on time and delivered a great-looking deck." }, { suburb: "Subiaco", type: "Composite Deck", rating: 5, review: "Fantastic results without overcharging. The quality really shows." }, { suburb: "Cottesloe", type: "Hardwood Deck", rating: 5, review: "The attention to detail really stood out. The deck looks incredible and the service was first class." }];
  return <div className="min-h-screen bg-background">
      <Header onQuoteClick={handleQuoteClick} />
      <section className="relative pt-32 pb-20 overflow-hidden"><div className="absolute inset-0 accent-gradient opacity-10"></div><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10"><div className="text-center max-w-4xl mx-auto"><div className="inline-flex items-center space-x-2 bg-primary/10 px-4 py-2 rounded-full mb-6"><MapPin className="w-4 h-4 text-primary" /><span className="text-sm font-medium text-primary">Servicing All Perth Suburbs</span></div><h1 className="text-4xl md:text-5xl font-bold text-foreground mb-6">Perth's Most Trusted<br /><span className="text-gradient">Decking Specialists</span></h1><p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">Professional decking installation and repair services across Greater Perth. Local tradies, trusted by 1,100+ Perth homeowners.</p><div className="flex flex-wrap gap-4 justify-center"><Button variant="quote" size="lg" onClick={handleQuoteClick}>Get Free Perth Quotes</Button><Button variant="outline" size="lg" asChild><a href="tel:0481752344" aria-label="Call 0481 752 344"><Phone className="w-4 h-4 mr-2" />Call 0481 752 344</a></Button></div></div></div></section>
      <section className="py-12 bg-muted/30"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-2 lg:grid-cols-4 gap-6">{stats.map((stat, index) => <Card key={index} className="text-center border-border/50"><CardContent className="p-6"><div className="w-12 h-12 accent-gradient rounded-full flex items-center justify-center mx-auto mb-3"><stat.icon className="w-6 h-6 text-white" /></div><div className="text-3xl font-bold text-foreground mb-1">{stat.value}</div><div className="text-sm text-muted-foreground">{stat.label}</div></CardContent></Card>)}</div></div></section>
      <section className="py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">We Service All Perth Suburbs</h2><p className="text-lg text-muted-foreground max-w-2xl mx-auto">From Joondalup to Rockingham, we've got Perth covered</p></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-8">{suburbs.map((suburb, index) => <SuburbLink key={index} suburb={suburb} cityPath="/perth" />)}</div>{showAllSuburbs && <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-8">{allSuburbs.map((suburb, index) => <SuburbLink key={index} suburb={suburb} cityPath="/perth" />)}</div>}<div className="text-center"><p className="text-muted-foreground mb-4">Don't see your suburb? We service the entire Greater Perth area!</p><Button variant="outline" onClick={() => setShowAllSuburbs(!showAllSuburbs)}>{showAllSuburbs ? <><ChevronUp className="w-4 h-4 mr-2" />Hide Suburbs</> : <><ChevronDown className="w-4 h-4 mr-2" />View All Suburbs</>}</Button></div></div></section>
      <section className="py-20 bg-muted/30"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">Recent Perth Projects</h2><p className="text-lg text-muted-foreground max-w-2xl mx-auto">See what your neighbours are saying about their decking projects</p></div><div className="grid md:grid-cols-3 gap-6">{recentProjects.map((project, index) => <Card key={index} className="hover-scale border-border/50"><CardContent className="p-6"><div className="flex items-center justify-between mb-4"><div className="flex items-center space-x-2"><MapPin className="w-4 h-4 text-primary" /><span className="font-semibold text-foreground">{project.suburb}</span></div><div className="flex items-center space-x-1">{[...Array(project.rating)].map((_, i) => <Star key={i} className="w-4 h-4 fill-primary text-primary" />)}</div></div><p className="text-sm text-muted-foreground mb-3">{project.type}</p><p className="text-sm text-foreground italic">"{project.review}"</p></CardContent></Card>)}</div></div></section>
      <section className="py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-12 items-center"><div><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-6">Why Perth Homeowners Choose Us</h2><div className="space-y-4"><div className="flex items-start space-x-3"><div className="w-6 h-6 accent-gradient rounded-full flex items-center justify-center flex-shrink-0 mt-1"><span className="text-white text-xs font-bold">✓</span></div><div><h3 className="font-semibold text-foreground mb-1">Local Perth Experts</h3><p className="text-muted-foreground text-sm">Local deck builders understand Perth's unique weather, council requirements, and local styles</p></div></div><div className="flex items-start space-x-3"><div className="w-6 h-6 accent-gradient rounded-full flex items-center justify-center flex-shrink-0 mt-1"><span className="text-white text-xs font-bold">✓</span></div><div><h3 className="font-semibold text-foreground mb-1">Fast Response Times</h3><p className="text-muted-foreground text-sm">Same-day quotes and flexible scheduling to suit your Perth lifestyle</p></div></div><div className="flex items-start space-x-3"><div className="w-6 h-6 accent-gradient rounded-full flex items-center justify-center flex-shrink-0 mt-1"><span className="text-white text-xs font-bold">✓</span></div><div><h3 className="font-semibold text-foreground mb-1">Quality</h3><p className="text-muted-foreground text-sm">Local expert deck builders on all installations.</p></div></div></div></div><div className="relative"><div className="aspect-[4/3] rounded-2xl overflow-hidden shadow-elegant"><img alt="Perth Decking Projects" className="w-full h-full object-cover" src="/lovable-uploads/5dc8e99f-d31f-45a3-82b0-2cbaf923d400.webp" /></div></div></div></div></section>
      <section className="py-20 bg-muted/30"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><div className="accent-gradient rounded-2xl p-12 shadow-elegant"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Get Your Perth Deck Built?</h2><p className="text-white/90 text-lg mb-8 max-w-2xl mx-auto">Join 1,000's of happy Perth homeowners. Get your free quotes in 60 seconds.</p><Button variant="secondary" size="lg" onClick={handleQuoteClick}>Get Free Perth Quotes</Button></div></div></section>
      <Footer />
    </div>;
};
export default Perth;